### ISSUE TITLE
Switch to boot

### ISSUE THREAD

**Issue by crisptrutski** [crisptrutski/matchbox#14]
@martinklepsch are there any downsides to moving over for libraries? I'm keen to give it a try

**Comment by martinklepsch** [comment]
@crisptrutski don't think there are any downsides but I'm slightly biased :)

**Comment by martinklepsch** [comment]
@crisptrutski if you run into any problems or have questions feel free to ping me in #hoplon on Freenode.

**Comment by crisptrutski** [comment]
Will tackle this on the weekend. Quite likely you'll be pestered :)

**Comment by crisptrutski** [comment]
@martinklepsch 

Decided to keep lein project around for contributors who prefer leiningen or use cursive.

Just need to get past the CLJSJS import issue or get CLJS test task working. There's https://github.com/pandeiro/boot-test-cljs, but I didn't have success with it, and also problematic that I'd need to vendor or instruct users to compile it themselves.

**Comment by crisptrutski** [comment]
@martinklepsch see there's talk about supporting `cljs.test` in `boot-test`. Do you know how far away this feature would be?

**Comment by martinklepsch** [comment]
> see there's talk about supporting cljs.test in boot-test.

Where did you see this? 

>  and also problematic that I'd need to vendor or instruct users to compile it themselves.

How do you mean that? As far as I understood `boot-test-cljs` is self-contained.
Maybe @pandeiro can give some advice here :smile:

**Comment by crisptrutski** [comment]
So technically there was talk (http://hoplon.discoursehosting.net/t/boot-cljs-test-runner/375), but I guess that's just outsider speculation / wishful thinking ;)

Well, `boot-test-cljs` just hasn't been released yet, so depending on it makes contribution to matchbox harder in the interim.

**Comment by pandeiro** [comment]
Hi @crisptrutski,

I have not released boot-test-cljs because in its current implementation, which makes use of boot-cljs, its `test-cljs` cannot be composed with another `cljs` task. (It works great otherwise, but I want users to have the option of using it in composition or standalone -- hence I'm not releasing it yet. But I do plan to re-implement the cljs compilation portion of the code and release it.)

In the meantime, there are other viable testing strategies for ClojureScript but they all involve a little manual legwork to get going, whether through lein or boot. I'm happy to chat about it in #clojurescript or #hoplon if you want.

**Comment by crisptrutski** [comment]
Noting what's left:

- [ ] Running CLJS tests
- [ ] Compiling examples

**Comment by martinklepsch** [comment]
Just learned about this: https://github.com/boot-cljs-test/node-runner 
CLJS test runner for node.

**Comment by crisptrutski** [comment]
Thanks, I'll check it out - although seem to recall underlying FB library not enjoying Node (trying to create iframes). When I get a chance hoping to finish https://github.com/pandeiro/boot-test-cljs/issues/2

**Comment by crisptrutski** [comment]
Version 0.0.8 has been built from scratch using boot

**Comment by martinklepsch** [comment]
:boom: :+1:

**Comment by martinklepsch** [comment]
Where is 0.0.8 though? :D

**Comment by crisptrutski** [comment]
In the garage: https://github.com/crisptrutski/matchbox/tree/reboot

Will get it roadworthy this week :vertical_traffic_light:

**Comment by martinklepsch** [comment]
Sweet!
