### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by podviaznikov** [crisptrutski/matchbox#31]
Is `swap` equivalent of firebase transaction https://www.firebase.com/docs/web/api/firebase/transaction.html?

**Comment by crisptrutski** [comment]
Precisely - it's a wrapper for that function. 

Realise my docs are lacking, so here's an overview of it:

1. Uses Firebase transaction, with `applyLocally` on. Currently there is no way to disable the optimistic updates, but there's a natural way I would add this to the API (will show below)
2. Function signature matches `clojure.core/swap!`, taking additional arguments to apply after the value i.e.`(m/swap! ref f a b c) => (f @ref a b c)`.
3. It supports taking a callback through a named-argument style: `(m/swap! ref f a b :callback cb)`

From 3 we see that the natural way to support control over local-first updates would be another keyword style argument, eg `(m/swap! ref f :skip-local true)`.

In my opinion having an optional parameter in variadic signature that defaults to true is a bit smelly, hence I would want to invert the option.

**Comment by crisptrutski** [comment]
Any suggestions around improving docs welcome - probably a "coming from Firebase" section would be good - probably too skewed towards the uninitiated.

Also API feedback is welcome. Are some of the synonyms more confusing than helpful?

**Comment by crisptrutski** [comment]
@podviaznikov I've added a quick overview of Matchbox API with references to Firebase equivalents here https://github.com/crisptrutski/matchbox/blob/826ceb8898ab5c8cd3b3bc56ba4e3d1adc8b66ce/README.md

**Comment by crisptrutski** [comment]
Also check out https://github.com/crisptrutski/matchbox/pull/23 - if there's interest for this higher level abstraction I'll merge it in and add docs.

**Comment by podviaznikov** [comment]
Thanks for the comment and updating the docs.
#23 looks interecting.
