### ISSUE TITLE
Control over when .val is called. Performance concern

### ISSUE THREAD

**Issue by mrmcc3** [crisptrutski/matchbox#35]
Hello

First off, cool library. I'm a big fan of Firebase and Clojure[Script]. In fact recently I did a bit of a brain dump and put some [code](https://github.com/mrmcc3/twigs) up. It only has support for basic stuff like references, snapshots and queries but I thought i'd share it here in case any of it is useful.

Anyway, according to the firebase people (see [this comment](https://groups.google.com/d/msg/firebase-talk/3NGhVYC_2Kw/mLJaKGZWUbUJ)) for performance reasons we should be using `.val` sparingly.

> Calling .val() is somewhat expensive. .val() is an O(n) operation that crawls the snapshot and creates an equivalent JavaScript object.  In addition to the O(n) algorithmic work, you're now storing two copies of the data (our internal snapshot and the copy you just created with .val()), so there's extra memory usage.

> Corollary: snapshot.val().foo.bar is more expensive than snapshot.child('foo').child'(bar').val()
Because .val() has to do an O(n) copy of the whole snapshot, it's better to call it at deeper levels if possible.

It seems matchbox just calls `.val` then `(js->clj v :keywordize-keys true)` on every event. While I can certainly understand the desire to get clojure[script] datastructures (because they rock) Is there a way to control at what level `.val` is actually called?

Cheers

**Comment by crisptrutski** [comment]
Hey Michael,

This is interesting - I didn't know that `.val()` created copies. Matchbox does not expose Snapshots at all, the idiom I've been following is to always scope at the reference. For `once` this always makes more sense to me, but the idea of separating snapshot sync with `on` and realising with `val` lazily is new to me. Use cases like plucking a single attribute from every member of a large collection spring to mind (your use case?). See that laziness and late scoping both solve real problems here.

> Is there a way to control at what level .val is actually called?
Beyond using `m/get-in` or passing korks to the listener, nope.

Looking at twigs, lots of good ideas there. Prefer the way you've shaved some of the chestnuts. Something between my [atom experiments](https://github.com/crisptrutski/matchbox/blob/master/src/matchbox/atom.cljx) and your snapshot wrappers appeals to me. Will tinker around when I get a chance and run things past you :)

**Comment by mrmcc3** [comment]
Yep it makes sense for `once`. Because of that recommendation by FB when using the javascript library I'm used to moving around the snapshot with `.forEach`, `.child` and only calling `.val` for the data I need. So i guess i wanted something similar in clojure[script]. Feel free to close this.

The atom stuff is interesting i'll definitely have more of a look. I haven't put too much thought into sync yet. For om most of the time I've gotten by with just setting up `(.on ref "value" cb) ` on `IWillMount` and `(.off ref "value" cb)` on `IWillUnmount` where `cb` just puts the wrapped-snapshot in the component/app state. But for more complex scenarios having the library manage the sync would be nice.

**Comment by crisptrutski** [comment]
No need to close, you've convinced me that snapshots should be exposed!

Personally dislike using lifecycle hooks to manage these subscriptions - prefer views to be as source-agnostic and stateless as possible. When working with Om, I try to really keep all state in the atom, so directives to start/stop syncing queries with portions of the atom is the approach I've taken. With Reagent, piping a query into a reactive atom has worked well in the small. With Re-frame you can cheat a little bit, and produce reactive atoms within a subscription, or use event handlers to control sync with the central db. When using query subscriptions, snapshot types would compose nicely (an extra `reaction` layer)

Dequeuing / delaying updates to the atom would be nice though, at the least limiting to requesting-animation-frame - playing around have added massive amounts of items to collection fully synced with atoms, and the data structure churn is not pretty (lots of GC)

Putting ref types (snapshot / delay) inside Atoms does not appeal to me, in early experiments I tried making references into cursors, but it felt too complex. Also limited in usefulness, and now cursors are deprecated.

Synchronisation does seem like a global concern to me - Firebase itself is global. At the global level you can start shaving off the costs of `.val` and `js->clj` also by sharing queries between components too.

If you have any ideas about Matchbox extensions to provide snapshots, feel free to propose or even PR. The API for matchbox is already a bit bloated though, I'm thinking of trimming down for 0.0.8.

**Comment by mrmcc3** [comment]
> When working with Om, I try to really keep all state in the atom, so directives to start/stop syncing queries with portions of the atom is the approach I've taken

Yep I wasn't entirely clear. I often setup start/stop syncing queries to `om/update!` a portion of the main atom / global app state with the wrapped-snapshot. I often manage these start/stop subscriptions in the `IWillMount`/`IWillUnmount` because in most cases if the component isn't mounted I don't require firebase to keep syncing. once the component is mounted again a `.on` is attached and firebase sends down fresh data.

**Comment by mrmcc3** [comment]
As for the rest I was thinking about writing a few examples #6 to get more familiar with matchbox first. I've done a couple of cljs projects with login/user pages powered by firebase and I've got a few common patterns that might make good examples.

**Comment by crisptrutski** [comment]
Version 0.0.8 (see WIP at [this branch](/crisptrutski/matchbox/tree/reboot)) will provide direct access to snapshots, and I believe support your use cases quite elegantly.

Found Twigs really stimulating, but ultimately decided to take another route.  Assume you're faithful to your project now, but keep in touch with any new ideas or criticism. Feel free to PR a link back to Twigs in this README if you want to share some of my light traffic :blue_car:
