### ISSUE TITLE
listen-children< causing infinite loop

### ISSUE THREAD

**Issue by afhammad** [crisptrutski/matchbox#36]
This causes an infinite loop even though there are only 4 children:

````clojure
(go-loop []
  (let [[event-type data] (<! (mb-async/listen-children< fbr [:users (:uid current-user) :contacts]))]
    (println event-type)
    (recur)))
````
while this works and only triggers callback 4 times:

````clojure
(mb/listen-children fbr [:users (:uid current-user) :contacts]
      (fn [[event-type data]]
        (println event-type)))
````

Is this a bug or am i doing something silly?

**Comment by crisptrutski** [comment]
Something silly I'm afraid! You're creating a new listener inside each `go-loop` iteration, hence getting a results every time. There's an additional issue here, that your loop does not have a terminating case - if the loop did use a consistent channel, but that channel was closed, then the channel would start yielding `nil` immediately, and the go block would go wild in an unrestrained spin loop.

Here's a very with a hoisted channel and a termination condition:

```clojure
(go-loop [ch (mb-async/listen-children< fbr [:users (:uid current-user) :contacts])]
  (when-let [[event-type data] (<! ch)]
    (println event-type)
    (recur ch)))
```

**Comment by afhammad** [comment]
I thought so! It was quite late. Thanks @crisptrutski!
