### ISSUE TITLE
twitter/facebook oath login

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#38]
Is there a way to a matchbox equivalent of the Firebase twitter/facebook OAuth?

i.e. the CLJS version of this
```js
var ref = new Firebase("https://<YOUR-FIREBASE-APP>.firebaseio.com");
ref.authWithOAuthRedirect("twitter", function(error) {
  if (error) {
    console.log("Login Failed!", error);
  } 
});
```

**Comment by crisptrutski** [comment]
There's no sugar for this, but you can use interop:

```clojure
(def ref (m/connect "https://<YOUR-FIREBASE-APP>.firebaseio.com"))
(.authWithOAuthRedirect("twitter", (fn [err] (when err (js/console.log "Login Failed!" err))))
```

Would take a PR to wrap any methods like this in `matchbox.core`, if that appeals to you

**Comment by continuata** [comment]
I seem to have figured out the answer to my own question ... I don't think you've created a wrapper function for it yet, anyway I just called it like this and it seemed to work

```clj
(def ref (m/connect "https://<YOUR-FIREBASE-APP>.firebaseio.com"))
(defn callback [error]
    (prn error))
(.authWithOAuthRedirect ref "twitter" callback)
```

**Comment by crisptrutski** [comment]
Oh snap! Glad you came right :smile:

**Comment by continuata** [comment]
yeah I may start some PRs ... I love this lib, just a few things I hit in it from time to time.
(plus the documentation)

**Comment by crisptrutski** [comment]
Extra hands welcome - it has gotten rather quiet here as I've been distracted..
