### ISSUE TITLE
Implementing Firebase Queue

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#39]
How would I go about implementing this using your API?
Would this work in JS interop?

```clj
(js/Queue. _ref (fn [data progress resolve reject]
    (prn data)
    (resolve))
```

**Comment by crisptrutski** [comment]
Hadn't actually come across Firebase Queue, thanks for bringing it to my attention. The interop you posted should work fine as Matchbox does not wrap the refs, and not sure if there's much point in creating a clojurescript binding over the constructor.

Would suggest wrapping the firebase-queue library in a cljsjs package to make bundling and externs easier.

**Comment by continuata** [comment]
Cool ... Will let you know when I've got it done.

**Comment by continuata** [comment]
Oh I didn't realise I can use CLJSJD straight off the bat without having to make my own library. That's fantastic

**Comment by crisptrutski** [comment]
Glad you came right!

Sending a PR at https://github.com/cljsjs/packages would still be welcome :)
