### ISSUE TITLE
Need wrapper for authWithCustomToken.

### ISSUE THREAD

**Issue by johanatan** [crisptrutski/matchbox#41]
It would be really nice if you could add the following function: :)

```
(defn auth-custom [^Firebase ref secret] (.authWithCustomToken ref secret identity))
```

**Comment by crisptrutski** [comment]
Well, it was nice of you to ask, so [sure](https://github.com/crisptrutski/matchbox/commit/b5e35a7862fba84bca2d7e991e78faf9b20f67dd). Maybe next time send a PR? :smile: 

Have updated `0.0.8-SNAPSHOT` - let me know if you have any issues!

**Comment by johanatan** [comment]
I didn't send the PR because I didn't know precisely how you wanted to
handle the cb. But I see now that it was pretty straightforward (following
the existing pattern-- minus the factorization of 'identity'). :)

**Comment by crisptrutski** [comment]
Feel free to "shoot first" with PRs - can always give feedback, or merge and then touch-up :gun:

**Comment by continuata** [comment]
How do I use this feature? 
I'm trying to do
```clj
(m/auth-custom (m/connect "https://FIREBASE.firebaseio.com") "SECRET_KEY" #(prn "connected"))
```
But I get 
```
Fri Sep 25 14:47:54 BST 2015 [WARN] AuthenticationManager: Received invalid auth data: {auth=null, expires=null}
Fri Sep 25 14:47:54 BST 2015 [WARN] AuthenticationManager: Received invalid auth data: null
Exception in thread "FirebaseEventTarget" clojure.lang.ArityException: Wrong number of args (2) passed to: request/eval20225/fn--20226
```

**Comment by crisptrutski** [comment]
The issue is the arity of your callback - `#(prn "connected")` takes no arguments, but it's being called with two.

Try: `(m/auth-custom (m/connect "https://FIREBASE.firebaseio.com") "SECRET_KEY" (fn [err auth-data] (prn "connected")))`

**Comment by continuata** [comment]
oh how stupid of me ... thanks
