### ISSUE TITLE
Admin level authentication

### ISSUE THREAD

**Issue by nicholasf** [crisptrutski/matchbox#43]
Hi,

Looking at `matchbox.async` I can see two auth functions, one for auth via email and password and another for anonymous auth.

How do you connect as an admin with a firebase secret?

**Comment by crisptrutski** [comment]
@nicholasf Thanks for pointing this out - I forgot that the auth functions where wrapped in that namespace. Will push a snapshot with those extra wrappers before tomorrow.

**Comment by crisptrutski** [comment]
@nicholasf published cec5372fd2f2f5c470e269518cf35154692a102e with the chan based version

**Comment by nicholasf** [comment]
Thanks @crisptrutski - will try it out today.
