### ISSUE TITLE
how to edit build and run locally

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#45]
this is not an issue with matchbox, it is purely my ignorance as a noob.

I'm wanting to make some contributions to this project and have a few new additions I may make some PRs on.
Anyway I've not built a CLJS package before ... I have the project forked and can obviously make changes, but how do I build/link to it in one of my local projects to try it out? 

I also tried simply editing the matchbox cljs files in my project to try out some hacks, which seemed to build the JS files and map files, but the project complained that there was "no such var" when I tried to use one of my new functions ... can you point me in the direction of somewhere to learn about how to do this and apologies again for posting on here.

**Comment by continuata** [comment]
I think I realise what the problem was with my local edits ;-)
I was changing the cljs files but using matchbox in clj files.

I've also figured out if I lein install my forked repo ... it'll build and put into a local repo,
just need to figure out how to symlink it and I'll be on my way.

**Comment by continuata** [comment]
ok sorted now ... I get it.

I rename the local fork with a new version, compile and install it and simply change the dependency in my other project, very nice.

**Comment by crisptrutski** [comment]
Sorry I wasn't around to help out - glad you found your way through. Looking forward to those juicy PRs ;)
