### ISSUE TITLE
FIREBASE WARNING: Exception was thrown by user callback

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#46]
I'm getting this warning, which results in no data from Firebase being handled, but only on my live Heroku version of the app. The local dev version works without errors. 

```
FIREBASE WARNING: Exception was thrown by user callback. TypeError: a.Be is not a function
```

I'm running the exact same code on my local machine ... do you have any idea what's going on here?
I'm concerned that something's gone crazy in minification or something like that.

**Comment by continuata** [comment]
ok found the culprit ... it does seem to be minification, changing a JS function call on an object to a different name inside the Firebase callback, it then throws an exception.
In CLJS I have a function call
```clj
(.getDoc editor)
```
It's getting minified to `a.Be()` ... the `a` is the editor object, but obviously function `Be` doesn't exist.

So, yup, this has nothing to do with Firebase or matchbox, and I just need to figure out now how to stop it from doing this.

**Comment by crisptrutski** [comment]
Sounds like you need to add some externs for the editor's signature

**Comment by continuata** [comment]
it's actually the cljsjs codemirror package.
https://github.com/cljsjs/packages/tree/master/codemirror

I've got it temporarily working by just using `:optimizations :whitespace` when building, but will definitely look at the externs for that package.
