### ISSUE TITLE
Configurable serialization non-JSON data

### ISSUE THREAD

**Issue by keeth** [crisptrutski/matchbox#51]
First off - thanks for matchbox, I absolutely love it.

One thing I ran into today:

```
(m/reset-in! ref [:somepath] {:foo :bar})
```
The above writes the string ":bar" to firebase - this is confusing since I sometimes want to grab say a list of keys from an object and write them back as values in other objects.  I'd like to not have to remember to un-keyword-ify the values before writing.  Not a huge deal but it was a bit confusing.  Thanks!

**Comment by crisptrutski** [comment]
Glad you're being productive!

Retaining the colon is actually intentional - matchbox is a bit opinionated, and will actually read the value back as a keyword (rather than a string with a colon). This should then work just-fine being used to then  read out of objects (the keyword will get turned into a string with `-in` flavour readers, and reading a complete structure back will result in the keys being keyword-ized)

Perhaps I'm misunderstanding where things trip you up and get frustrating - eg. another system is reading those values?

Open to breaking changes if things can be made even easier :smile:

**Comment by keeth** [comment]
Yes I have other systems (a React Native app) consuming these values.  For the most part, the way matchbox handles keywords is very nice - I make heavy use of the *-in readers and writers. My problem is something like the following, I have a chat room with a list of members:

```
"members" : {
          "-K5JnkaKivM1wqr50uC9" : {
            "username" : "bob"
          },
          "-K5JxL8KA1MdajECEZOa" : {
            "username" : "kevin"
          },
          // etc
          }

```
I grab the object with get-in and do something like (-> room :members keys) to grab the keys (user ids), then I write some other object using each of those user ids like:

(m/reset-in! root [:lookupUserByFoo foo-id ] user-id)

the result is a path like 

/lookupUserByFoo/-K9hRT_08HuPYf4nsQaI/:-K5JxL8KA1MdajECEZOa

So the keys of the new object are correctly converted to string without colon but the value contains a colon.  This is surprising because in my time using matchbox I've come to expect it to always remove the colons when writing, especially since these are basically unique/foreign keys and so they need to be preserved exactly.  I guess because I've always been building with non-clojure system interop in mind it never occurred to me to write a keyword value and expect it to be read back as a keyword.

I wonder if a halfway measure would be to check if the value being written looks like a firebase ID and not write the colon in that case.

**Comment by crisptrutski** [comment]
Wondering if it's worth just making the [serialization layer](https://github.com/crisptrutski/matchbox/blob/master/src/matchbox/core.cljx#L129-L139) swappable, eg. opt completely out of the magic-keywords business, or on the other scale support custom types.

In the world of already-magic keyword handling, your suggestion makes sense. Some questions (with trivial answers that look silly)

1. Would want to skip keywordization when reading these FUUID keys, so `(get (m/get ref "collection") (m/get ref "key"))` still works.
2. We'd lose the ability to `(let [key (m/get ref "key")] (key (m/get ref "collection")))`
3. In (rather exotic) collections that have mixed FUUID and regular keys, is it OK for the matchbox to create collection with mixed type keys? 

(FUUID standing for Firebase Push ID)

As far as recognising FUUIDs, can you think of a robust method for this? 20 character alphanumeric seems to lenient, and parsing for valid timestamp would be too slow :sweat_smile:

**Comment by crisptrutski** [comment]
For swapping out serialization, some ideas:

1. Global config (swaps out the relevant functions)
2. Scoped - let user define the pair against a FB reference. Use a multimethod on this field to make the functions extensible

PRs welcome to take a stab at this sort of thing, or I could hazard something

**Comment by keeth** [comment]
> As far as recognising FUUIDs, can you think of a robust method for this?

not really.. seems like it would be hard to do consistently.  it would be a way to avoid a breaking change, but probably not worth the added complexity.

> Some caveats/questions:

Ya I understand that there are some nice tricks you can do if you store keywords as keywords.  I never thought of doing that, probably because I have mixed-language project.  

> For swapping out serialization, some ideas:

I like the idea of global config, so that everyone can get the behavior they want in a straightforward way.

I think personally I would make the default serialization the same for keys and values: calling _name_ rather than _str_ on keywords.  But I understand both sides of this have merit.

Not sure if I'll have the cycles to attempt a PR, but I'll see.  Don't let me stop you if you have something in mind.

**Comment by crisptrutski** [comment]
@keeth still an issue?

**Comment by crisptrutski** [comment]
This is now supported with `(matchbox.serialization.plain/set-default!)` (with push a SNAPSHOT tonight)
