### ISSUE TITLE
Querying Firebase aka Filtering Refs

### ISSUE THREAD

**Issue by pate** [crisptrutski/matchbox#60]
Is it possible to do server-side filtering of Firebase entities with Matchbox? I can't find any mention of `filter` in the codebase.

Alternatively, can I pass an arbitrary Firebase ref that has some query on it? If yes, example please?

**Comment by crisptrutski** [comment]
Firebase filtering is explained here: [firebase docs](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries)

It's quite a different contract, so didn't alias to `filter-*`. If you have API suggestions there I'd be interested.

Relevant Matchbox functions:

```
m/start-at
m/end-at
m/equal-to
```

**Comment by crisptrutski** [comment]
PRs welcome to mention this in README or examples
