### ISSUE TITLE
Error in NodeJS

### ISSUE THREAD

**Issue by naartjie** [crisptrutski/matchbox#64]
@crisptrutski, you asked if it works in Node #59.

I am getting `Error: No transports available` presumably because firebase doesn't know where to find websocket.

The firebase npm module exports 2 versions of the lib, one for browser and another for node:
<img width="263" alt="screen shot 2016-04-06 at 20 27 21" src="https://cloud.githubusercontent.com/assets/514563/14328212/0668a0cc-fc36-11e5-9115-6ae9e41eea87.png">

Any pointers how I could tweak things to make matchbox use the node module instead of the web one? I presume cljsjs only packages the browser one, but the externs should be the same, as the API is the same.

Thanks for a cool lib!

**Comment by crisptrutski** [comment]
Thanks for looking into this @naartjie 👍 

Created a [PR for CLJSJS](https://github.com/cljsjs/packages/pull/541) - when that's approved and deployed usage should be as simple as adding `cljsjs.firebase-node` to your dependencies and adding `cljsjs.firebase` to `:exlcusions` for your matchbox dependency 😄

**Comment by crisptrutski** [comment]
@naartjie `[cljsjs/firebase_node "2.4.2-0"]` has been released - let me know if you run into any issues with it :octocat: 

PR to add Node.js tests to Matchbox would be joyously accepted 😄

**Comment by naartjie** [comment]
Awesome, that's very cool, thanks a lot @crisptrutski. I'll take it for a spin soon, and let you know if there are any issues.

re: PR for Node.js tests: n00b questions, but how would this work? Would you need to run it as a separate test run, i.e. have separate browser tests and node.js tests?

**Comment by crisptrutski** [comment]
Exactly, we'd need to launch the test run separately (`node` instead of `phantomjs`)

The excellent library [doo](https://github.com/bensu/doo) makes switching test runners a breeze. We'll probably need to move from `com.cemerick/clojurescript.test` to `cljs.test` to leverage that though. And if we're going to all that trouble, would favour going straight to `boot` and `boot-cljs-test`.

But I'm biased there 😄

**Comment by crisptrutski** [comment]
Just adding another test profile running through Node would be swell less-yacks-shaved step 💃

**Comment by crisptrutski** [comment]
@naartjie Switched test runners and made a stub for testing with Node #70 

Looks like the CLJSJS package needs some love still
