### ISSUE TITLE
Missing authentication types

### ISSUE THREAD

**Issue by flyboarder** [crisptrutski/matchbox#65]
Missing popup auth and redirect auth.

**Comment by crisptrutski** [comment]
Thanks for the notice - haven't had a use for either flow myself, nor the time to spare to play completionist. 

This should be an easy contribution, if you're interested - otherwise I recommend just using the JS interface directly on a Matchbox ref with inter-op.

**Comment by flyboarder** [comment]
I can send some PRs but I don't have a use case for JVM testing. Also I don't see an example for simply fetching a value, without mutability. Perhaps I'm missing something. 

Sent from Outlook Mobile




On Thu, Apr 21, 2016 at 3:12 PM -0700, "Chris Truter" <notifications@github.com> wrote:












Thanks for the notice - haven't had a use for either flow myself, nor the time to spare to play completionist. 



This should be an easy contribution, if you're interested - otherwise I recommend just using the JS interface directly on a Matchbox ref with inter-op.

**Comment by crisptrutski** [comment]
Fetching a value - what about `m/deref`?

Since the JVM library does not have equivalent auth methods, no need to worry about them - just implement for CLJS.

**Comment by flyboarder** [comment]
I have tried that, how could i go about blocking and wait for the value?

**Comment by crisptrutski** [comment]
There's no way to block in Javascript/ClojureScript so there's only a non-blocking API there.

**Comment by crisptrutski** [comment]
Hope you come right with the blocking issue - closing this issue as I've released `0.0.9` with the OAuth methods wrapped.
