### ISSUE TITLE
Provide a sync-* method that preserves the ordering in firebase while giving access to the key.

### ISSUE THREAD

**Issue by dotboris** [crisptrutski/matchbox#73]
I'm currently making use of the `sync-r` method in `matchbox.reagent` to connect my reagent app with firebase with ease. I noticed that the elements in the `r/atom` returned by `sync-r` are not in the right order. I expect them to be in the same order as they are found in firebase.

In my app, I make use of `conj!` to get firebase to generate keys. What's great about this is that firebase offers some guaranties about the order of items when using `.push()` (or `conj!` in this case). I was hoping to be able to leverage those guaranties.

My guess is that I'm having this issue because `sync-r` returns a `map` which has no guaranties about order. Would it be possible to get an alternative to `sync-r` that returns a `sorted-map` instead of a regular `map`?

I should mention that I am aware of `sync-list` and from what I can tell it does respect ordering. My issue with it is that it doesn't give me access to the key of each element.

**Comment by crisptrutski** [comment]
Hey @dotboris - your desire is a totally reasonable one. Would accept a PR to switch to `sorted-map`, doubt there's significant overhead compared to going immutable.

**Comment by crisptrutski** [comment]
Ping @dotboris - is this still a bother? Thinking of just making sorted maps the default at the mapping layer when "immutalising" data snapshots. And this could be backed out of using a mechanism like discussed in #51. 

Have a little bit of time to spread between OSS projects this evening, so let me know if this is valuable to you.

**Comment by dotboris** [comment]
@crisptrutski Yes this is still a bother and I would find this valuable.
