### ISSUE TITLE
Firebase externs

### ISSUE THREAD

**Issue by naartjie** [crisptrutski/matchbox#78]
Just a heads up, the firebase npm module now publishes their [externs](https://www.npmjs.com/package/firebase#api-definition). I understand this wasn't the case before, so I wanted to put that on the radar.

**Comment by martinklepsch** [comment]
It seems this is done already: https://github.com/cljsjs/packages/blob/master/firebase/build.boot

🎉

**Comment by naartjie** [comment]
thanks @martinklepsch and sorry for opening this up in the wrong repo in the first place, doh.

**Comment by martinklepsch** [comment]
hah, no worries! good to have it somewhere :)
